### ISSUE TITLE
Redundant backend/springboot folder

### ISSUE THREAD

**Issue by wubin1989** [Tsingxiao/unionj-generator#5]
I used below code to generate proto and vo folder. It works well. But redundant backend/springboot folder generated.

SpringbootFolderGenerator springbootFolderGenerator = new SpringbootFolderGenerator
        .Builder(backend)
        .protoPackageName("xx.xx.proto")
        .protoOutputDir("xx/xx/proto")
        .voPackageName("xx.xx.vo")
        .voOutputDir("xx/xx/vo")
        .build();
    springbootFolderGenerator.generate();

**Comment by TQCCC** [comment]
ok, fix it: https://github.com/Tsingxiao/unionj-generator/pull/7
